/**
 * Lets the clock appear on a locked phone.
 *
 * `android/` is generated by prebuild and never committed, so these two
 * attributes have to be re-applied every time the project is generated —
 * which is what a config plugin is for.
 *
 *   showWhenLocked  the activity may draw over the lock screen
 *   turnScreenOn    starting it wakes the display
 *
 * Both are manifest attributes rather than runtime calls because the activity
 * has to carry them before it is created: the screen saver starts it on a
 * phone whose screen is off, and by the time any code of ours runs it is too
 * late to ask for either.
 *
 * Neither unlocks anything. They let this one activity show above the lock
 * screen, the way an alarm or a navigation prompt does; the rest of the phone
 * stays locked, and the keyguard is still there when the clock is dismissed.
 *
 * None of it does anything until the user picks Kiosk under
 * Settings -> Display -> Screen saver. An app cannot nominate itself.
 */

const { withAndroidManifest } = require('expo/config-plugins');

module.exports = function withLockScreenDock(config) {
  return withAndroidManifest(config, (mod) => {
    const application = mod.modResults.manifest.application?.[0];
    if (!application) return mod;

    const activities = application.activity ?? [];
    const main = activities.find(
      (activity) => activity.$?.['android:name'] === '.MainActivity',
    );
    if (!main) {
      throw new Error(
        'withLockScreenDock: no .MainActivity in the manifest. The template ' +
          'changed its name, and these attributes would have gone nowhere.',
      );
    }

    main.$['android:showWhenLocked'] = 'true';
    main.$['android:turnScreenOn'] = 'true';

    return mod;
  });
};
