/**
 * Release signing and version code, injected into the generated Gradle project.
 *
 * `android/` is generated by prebuild and never committed, so the signing
 * config cannot simply be edited into build.gradle by hand — it has to be
 * re-applied every time the project is generated. That is what a config plugin
 * is for.
 *
 * The upload key is supplied entirely from outside the repository: CI decodes
 * it from a secret and passes four Gradle properties. When those properties are
 * absent — which is every local build, and every build by anyone who has not
 * set the secrets up — the release type falls back to the debug keystore, so a
 * sideloadable APK still comes out and nothing breaks. That fallback is a
 * convenience, not a shipping path: an APK signed with the debug key is signed
 * with a key everyone in the world already has.
 *
 * Nothing secret lives here. This file names the properties; it never contains
 * them.
 */

const { withAppBuildGradle } = require('expo/config-plugins');

/** Gradle property names. CI passes these with -P. */
const STORE_FILE = 'KIOSK_UPLOAD_STORE_FILE';
const STORE_PASSWORD = 'KIOSK_UPLOAD_STORE_PASSWORD';
const KEY_ALIAS = 'KIOSK_UPLOAD_KEY_ALIAS';
const KEY_PASSWORD = 'KIOSK_UPLOAD_KEY_PASSWORD';

const UPLOAD_CONFIG = `
        upload {
            // Populated only when CI has supplied the key. Referencing the
            // properties unconditionally would break every build without them.
            if (project.hasProperty('${STORE_FILE}')) {
                storeFile file(project.property('${STORE_FILE}'))
                storePassword project.property('${STORE_PASSWORD}')
                keyAlias project.property('${KEY_ALIAS}')
                keyPassword project.property('${KEY_PASSWORD}')
            }
        }`;

const RELEASE_SIGNING = `signingConfig project.hasProperty('${STORE_FILE}') ? signingConfigs.upload : signingConfigs.debug`;

function addUploadConfig(contents) {
  if (contents.includes('upload {')) return contents;

  // Appended inside signingConfigs, straight after the debug block the
  // template always emits.
  const anchor = `    signingConfigs {`;
  const at = contents.indexOf(anchor);
  if (at === -1) {
    throw new Error('withReleaseSigning: no signingConfigs block to extend');
  }

  const close = contents.indexOf('\n    }', at);
  if (close === -1) {
    throw new Error('withReleaseSigning: signingConfigs block is unterminated');
  }

  return contents.slice(0, close) + UPLOAD_CONFIG + contents.slice(close);
}

function useUploadKeyForRelease(contents) {
  // The template hands the release build the debug key with a comment saying
  // not to ship it. There are two `signingConfig signingConfigs.debug` lines —
  // one in the debug build type, one in release — and only the second moves.
  const marker = '        release {';
  const at = contents.indexOf(marker);
  if (at === -1) throw new Error('withReleaseSigning: no release build type');

  const head = contents.slice(0, at);
  const tail = contents
    .slice(at)
    .replace('signingConfig signingConfigs.debug', RELEASE_SIGNING);

  return head + tail;
}

function setVersionCode(contents) {
  const raw = process.env.KIOSK_VERSION_CODE;
  if (!raw) return contents;

  const code = Number(raw);
  if (!Number.isInteger(code) || code < 1) {
    throw new Error(`withReleaseSigning: KIOSK_VERSION_CODE must be a positive integer, got ${raw}`);
  }

  // Play rejects an upload whose version code is not higher than the last one,
  // so this is driven by the CI run number rather than by a number in the repo
  // that somebody has to remember to raise.
  return contents.replace(/versionCode\s+\d+/, `versionCode ${code}`);
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (gradle) => {
    if (gradle.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning: expected a Groovy build.gradle');
    }

    let contents = gradle.modResults.contents;
    contents = addUploadConfig(contents);
    contents = useUploadKeyForRelease(contents);
    contents = setVersionCode(contents);
    gradle.modResults.contents = contents;

    return gradle;
  });
};
