/**
 * Release packaging settings for cheap, storage-poor Android devices.
 *
 * `android/` is generated by prebuild and never committed, so — exactly as
 * with the signing config — none of this can be edited into the Gradle project
 * by hand. It has to be re-applied every time the project is generated.
 *
 * Everything here is expressed as a Gradle property rather than as an edit to
 * build.gradle, because the app/build.gradle the template emits already reads
 * these three properties. Verbatim, from the template:
 *
 *     def enableMinifyInReleaseBuilds =
 *         (findProperty('android.enableMinifyInReleaseBuilds') ?: false).toBoolean()
 *     ...
 *     def enableShrinkResources =
 *         findProperty('android.enableShrinkResourcesInReleaseBuilds') ?: 'false'
 *     shrinkResources enableShrinkResources.toBoolean()
 *     minifyEnabled enableMinifyInReleaseBuilds
 *     proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
 *
 * and `reactNativeArchitectures` is read by the React Native Gradle plugin,
 * which turns it into `defaultConfig.ndk.abiFilters`
 * (NdkConfiguratorUtils.kt: "abiFilters are split ABI are not compatible each
 * other, so we set the abiFilters only if the user hasn't enabled the split
 * abi feature" — this project does not enable ABI splits, so the filter
 * applies).
 *
 * Setting a property is therefore a change to an interface the generated
 * project already offers, not a rewrite of generated Gradle. Each one can also
 * be overridden at the command line without touching this file, e.g.
 * `./gradlew assembleRelease -PreactNativeArchitectures=x86_64`.
 *
 * The keep rules are appended to the generated app/proguard-rules.pro, since
 * that file is on the `proguardFiles` line above.
 */

const fs = require('fs');
const path = require('path');

const { withGradleProperties, withDangerousMod } = require('expo/config-plugins');

/**
 * Only the two ARM ABIs.
 *
 * The template ships armeabi-v7a, arm64-v8a, x86 and x86_64, and a universal
 * APK carries all four — most of its bytes are the four copies of
 * libreactnative.so, libhermesvm.so and the Reanimated/Worklets libraries.
 * Nothing this app targets is x86: those two ABIs exist for emulators and for
 * the handful of x86 Chromebooks. Dropping them roughly halves the native
 * payload of the sideload APK, which is the copy that has to fit on a device
 * with a few hundred megabytes free.
 *
 * The .aab loses them too. That costs nothing at install time, because Play
 * already serves one ABI per device; it only means Play will not serve this
 * app to an x86 device at all.
 *
 * Both ARM ABIs stay. arm64-v8a alone would be smaller still, but 1 GB
 * Android 7 hardware is frequently 32-bit-only, and that is precisely the
 * hardware this is for.
 */
const ARCHITECTURES = 'armeabi-v7a,arm64-v8a';

const PROPERTIES = [
  {
    key: 'android.enableMinifyInReleaseBuilds',
    value: 'true',
    comment: [
      'Run R8 over release builds.',
      '',
      'Off by default in the React Native template. This app pulls in Jetpack',
      'Compose, Material 3 and OkHttp transitively — expo-router depends on',
      "@expo/ui, which is autolinked — and uses almost none of it. Shrinking is",
      'what removes that.',
    ],
  },
  {
    key: 'android.enableShrinkResourcesInReleaseBuilds',
    value: 'true',
    comment: [
      'Drop resources nothing references. Requires minification, above.',
      '',
      'Same reason: the Material and Compose resource tables come in whole and',
      'this app draws none of it. AGP shrinks resources in its safe mode, which',
      'keeps anything that might be reached through Resources.getIdentifier.',
    ],
  },
  {
    key: 'reactNativeArchitectures',
    value: ARCHITECTURES,
    comment: null, // The template already comments this one, accurately.
  },
];

/** The block appended to app/proguard-rules.pro, fenced so it can be found again. */
const RULES_BEGIN = '# --- kiosk release rules (generated) ---';
const RULES_END = '# --- end kiosk release rules ---';

const RULES = `
${RULES_BEGIN}

# Shrink and optimize, but do not rename.
#
# Renaming is where R8 breaks a React Native app: every lookup by class name —
# and there are several, in React Native's own view-manager and module-info
# paths, in Expo's module registry, and in libraries that ship no rules of
# their own — has to be anticipated exactly or it fails at run time, not at
# build time. Shrinking is where nearly all of the size win is; renaming adds
# maybe a tenth of the dex on top and is the whole of the risk.
#
# It also means a crash on the docked device produces a readable stack trace
# without anyone having to find the matching mapping file.
#
# Once a minified build has been run on real hardware and the app is known to
# work, dropping this line is the next size win available.
-dontobfuscate

# Keep the metadata reflective code reads. proguard-android.txt already keeps
# annotations; Signature and the inner-class attributes matter for Kotlin
# generic types, which is how expo-modules-core resolves the argument types of
# a module function at call time.
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod

# This app's own native module.
#
# The listener is named in AndroidManifest.xml and constructed by the system,
# never referenced from code. AGP derives a keep rule for manifest components
# on its own; this says so explicitly rather than depending on that inference,
# because losing it would silently disable notification access and with it the
# whole now-playing feature.
-keep class expo.modules.nowplaying.KioskNotificationListener { *; }
-keep class expo.modules.nowplaying.NowPlayingModule { *; }

# Libraries that ship no consumer rules of their own.
#
# react-native, expo-modules-core, react-native-reanimated,
# react-native-worklets and react-native-svg all declare consumerProguardFiles,
# so their rules arrive with them and are not repeated here. These five do not,
# and all five are reached from JNI or from the generated package list rather
# than from ordinary call sites, which is what R8 cannot see.
-keep class com.swmansion.gesturehandler.** { *; }
-keep class com.swmansion.rnscreens.** { *; }
-keep class com.th3rdwave.safeareacontext.** { *; }
-keep class com.reactnativevolumemanager.** { *; }
-keep class com.reactnativecommunity.asyncstorage.** { *; }

# Optional dependencies that are compiled against but never shipped.
#
# R8 in full mode — the AGP 8 default — fails the build on a reference to a
# class it cannot find, rather than warning. These are the usual absentees:
# annotation-only artifacts, and the alternative TLS providers OkHttp supports
# but does not depend on. Silencing a reference to a class that is in fact
# present is harmless, so listing them up front costs nothing and saves a
# round trip through CI.
-dontwarn javax.annotation.**
-dontwarn javax.inject.**
-dontwarn com.google.errorprone.annotations.**
-dontwarn com.google.j2objc.annotations.**
-dontwarn org.checkerframework.**
-dontwarn org.jetbrains.annotations.**
-dontwarn com.facebook.infer.annotation.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**

${RULES_END}
`;

/**
 * Set a property, replacing the template's value in place when it already has
 * one so the file keeps its existing shape and comments.
 */
function setProperty(properties, { key, value, comment }) {
  const at = properties.findIndex((item) => item.type === 'property' && item.key === key);

  if (at !== -1) {
    properties[at] = { type: 'property', key, value };
    return properties;
  }

  if (comment) {
    properties.push({ type: 'empty' });
    for (const line of comment) properties.push({ type: 'comment', value: ` ${line}`.trimEnd() });
  }
  properties.push({ type: 'property', key, value });

  return properties;
}

function withGradleFlags(config) {
  return withGradleProperties(config, (gradle) => {
    for (const property of PROPERTIES) setProperty(gradle.modResults, property);
    return gradle;
  });
}

function withKeepRules(config) {
  return withDangerousMod(config, [
    'android',
    (mod) => {
      const file = path.join(mod.modRequest.platformProjectRoot, 'app', 'proguard-rules.pro');
      const existing = fs.readFileSync(file, 'utf8');

      // prebuild without --clean leaves the previous android/ in place and
      // re-runs the mods over it, so appending has to be idempotent. Replace
      // the fenced block rather than adding a second copy.
      const from = existing.indexOf(RULES_BEGIN);
      const next =
        from === -1
          ? existing.trimEnd() + '\n' + RULES
          : existing.slice(0, from) + RULES.trimStart() + existing.slice(existing.indexOf(RULES_END) + RULES_END.length + 1);

      fs.writeFileSync(file, next);
      return mod;
    },
  ]);
}

module.exports = function withReleaseOptimization(config) {
  return withKeepRules(withGradleFlags(config));
};
